### ISSUE TITLE
hook.js:608 CodeMirror plugin crashed: TypeError: tags3 is not iterable

### ISSUE THREAD

**Issue by sergeysova** [uiwjs/react-codemirror#693]
I am using:
- pnpm 9.12.2 (monorepo)
- vite 5.4.10
- macOS 15.0.1
- Arc Browser 1.65.0
- react 18.3.1
- react-dom 18.3.1
- @hello-pangea/dnd 17.0.0
- @uiw/react-codemirror 4.23.5
- @uiw/codemirror-theme-vscode 4.23.5
- @uiw/codemirror-extensions-langs 4.23.5

Code:

```tsx
<CodeMirror
  basicSetup={false}
  extensions={[
    basicSetup({
      foldGutter: true,
      lineNumbers: true,
      highlightActiveLineGutter: true,
      syntaxHighlighting: true,
      tabSize: 2,
    }),
    langs.tsx(),
  ]}
  // extensions={[loadLanguage("typescript")!]}
  // extensions={[loadLanguage("shell")!]}
  // extensions={[basicSetup(), loadLanguage(content.language as LanguageName)!]}
  // extensions={[langs.javascript(), langs.tsx(), langs.typescript()]}
  value={content.code}
  onChange={handleCodeChange}
/>
```

I have multiple instances of <CodeMirror> on a single page. Each wrapped in DnD context.

But it doesn't highlight syntax. When I tried to add langs, it throws an error and renders without syntax highlighting:

```
CodeMirror plugin crashed: TypeError: tags3 is not iterable
    at _HighlightStyle.style (index.js:261:29)
    at highlightTags (index.js:278:33)
    at HighlightBuilder.highlightRange (index.js:365:22)
    at highlightTree (index.js:306:13)
    at TreeHighlighter.buildDeco (index.js:1777:13)
    at new TreeHighlighter (index.js:1755:33)
    at _ViewPlugin.create (index.js:2475:42)
    at PluginInstance.update (index.js:2494:44)
    at new _EditorView (index.js:7423:20)
    at useCodeMirror.js:83:27 Error Component Stack
    at index.js:15:7

... internal files from my project are stripped for clarity

  | commitPassiveMountEffects_complete | @ | react-dom.development.js:24930
  | commitPassiveMountEffects_begin | @ | react-dom.development.js:24917
  | commitPassiveMountEffects | @ | react-dom.development.js:24905
  | flushPassiveEffectsImpl | @ | react-dom.development.js:27078
  | flushPassiveEffects | @ | react-dom.development.js:27023
  | (anonymous) | @ | react-dom.development.js:26808
  | workLoop | @ | scheduler.development.js:266
  | flushWork | @ | scheduler.development.js:239
  | performWorkUntilDeadline | @ | scheduler.development.js:533
```

If there is no language extensions added, there is no errors is thrown, but also no syntax highlighting.

It throws with actually any language from `@uiw/codemirror-extensions-langs`.

Sadly almost unusable package(((

**Comment by sergeysova** [comment]
Ok. Actually deleted pnpm-lock.yaml, node_modules, dist and reinstalled.
Actually fixed.

Insane!
